name: dishhq
description: Dish allows you to save hours of development time every week with powerful SDKs
version: 0.0.3
author:
homepage: https://github.com/synapsecode/flutter-dishhq.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: